spring:
  application:
    name: gtech19
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sha1.clusters.zeabur.com:32660/gdspace?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mSzdb8PA2Q0uU416J79HoxchD5XB3ZKE

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.gtech19.model
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080