spring:
  application:
    name: gtech19
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sha1.clusters.zeabur.com:32660/gdspace?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mSzdb8PA2Q0uU416J79HoxchD5XB3ZKE
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    # 日期格式化（适用于 java.util.Date 类型）
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区设置（关键！避免时区偏移，使用东八区）
    time-zone: GMT+8
    # 对 Java 8 时间类型（LocalDateTime、LocalDate 等）的格式化
    deserialization:
      adjust-dates-to-context-time-zone: false  # 禁用时区自动调整
    datetime-format: yyyy-MM-dd HH:mm:ss  # Java 8 时间类型的格式

# 火山引擎大模型API配置
volcano:
  api:
    token: bd747896-e89b-46f4-a5ab-0a232d086845  # Bearer Token
    url: https://ark.cn-beijing.volces.com/api/v3/chat/completions  # 文本生成API地址

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.gtech19.model
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

# 启用Swagger文档
swagger:
  enabled: true

chat:
  init-task:
    system: init_task_system_prompt.txt
    user: init_task_user_prompt.txt
  create-task-detail:
    system: create_task_detail_system_prompt.txt
    user: create_task_detail_user_prompt.txt
  task-report:
    system: task_report_system_prompt.txt
    user: task_report_user_prompt.txt
  task-chat:
    system: task_chat_system_prompt.txt
    user: task_chat_user_prompt.txt
